#!/usr/bin/env node

execFile = require('child_process').execFile;

amqp = require('./amqp');
fs   = require('fs');
sys  = require('sys');

debug = false;
if (process.env['UR_DEBUG']) {
  debug = true;
}

var creds
  = { host:     process.env['AMQP_HOST']      || 'localhost'
    , port:     process.env['AMQP_PORT']      || 5672
    , login:    process.env['AMQP_LOGIN']     || 'guest'
    , password: process.env['AMQP_PASSWORD']  || 'guest'
    , vhost:    process.env['AMQP_VHOST']     || '/'
    };

var nodeUUID;
var exchange;

var connection = amqp.createConnection(creds);

connection.addListener('error', function (e) {
  sys.log('AMQP connection error: ' + e.message);
});

connection.addListener('close', function (e) {
  console.log("Connection close");
});

// Wait until connection is made.
connection.addListener('ready', function (e) {
  console.log("AMQP Ready");


  // Grab the sysinfo and publish a startup message indicating we've come
  // online and are ready to receive requests.
  loadSysinfo(function (error, exitStatus, stdout, stderr) {
    if (error) {
      console.log("sysinfo error: " + stderr.toString());
      console.dir(arguments);
      return;
    }

    // output of sysinfo is a JSON object
    var sysinfo = JSON.parse(stdout);

    // Use the UUID param to uniquely identify this machine on AMQP.
    nodeUUID = sysinfo['UUID'];
    if (!nodeUUID) {
      throw new Error("Could not find 'UUID' in `sysinfo` output.");
    }

    // Open queue to receive our messages on and then set a handler for
    // 'execute' messages.
    var queue = connection.queue('ur.request.'+nodeUUID);
    queue.bind('amq.topic', 'ur.execute.#');
    queue.subscribeJSON(onExecute);

    // Open the exchange where we will publish outbound messages.
    exchange = connection.exchange('amq.topic', { type: 'topic' });

    exchange.publish('ur.startup.' + nodeUUID, sysinfo);
  });
});

function onExecute (m) {
  console.log("Received a message.");
  // Save the request id so we can reference it in the reply's routing key.
  var reqID = m._routingKey.split('.', 4)[3];
  switch (m.type) {
    case 'file':
      executeFile
        ( m.file
        , m.env
        , m.args
        , function (exitStatus, stdout, stderr) {
            publishExecuteReply(reqID, exitStatus, stdout, stderr);
          });
      break;
  
    case 'script':
      executeScript
        ( m.script
        , m.env
        , m.args
        , function (exitStatus, stdout, stderr) {
            publishExecuteReply(reqID, exitStatus, stdout, stderr);
          });
      break;
  }
}

// Execute a file and then call callback with captured output and exit status
// code.
function executeFile(filename, env, args, callback) {
  console.log("Executing file: " + filename);
  execFile
    ( filename
    , args || []
    , env ? { env: env } : {}
    , function (error, stdout, stderr) {
        if (error) {
          callback(error.code, stdout.toString(), stderr.toString());
          return;
        }
        callback(0, stdout.toString(), stderr.toString());
      }
    );
}

// Execute a script string.
function executeScript(script, env, args, callback) {
  console.log("Executing script: " + script);
  var filename = tmpFilename();
  console.log("Writing file " + filename);

  // Write file, 'chmod 700' it, run it, delete file.
  fs.writeFile(filename, script, function () {
    fs.chmod(filename, 0700, function () {
      executeFile(filename, env, args, function () {
        var execArgs = arguments;
        fs.unlink(filename, function () {
          callback.apply(undefined, execArgs);
        });
      });
    });
  });
}

// Publish an 'ur.execute-reply'-type message to AMQP.
function publishExecuteReply(reqID, exitStatus, stdout, stderr) {
  console.log("Publishing execute-reply to request " + reqID + ".");
  exchange.publish
    ( 'ur.execute-reply.' + nodeUUID + '.' + reqID
    , { exit_status: exitStatus
      , stdout:      stdout
      , stderr:      stderr
      }
    );
}

// Quick and dirty generation of tmp filenames.
function tmpFilename() {
  return "/tmp/ur-" + genId();
}

// Run the sysinfo script and return the captured stdout, stderr, and exit
// status code.
function loadSysinfo (callback) {
  var paramsExecutable
    = debug ? './sysinfo-fake.sh' : '/usr/bin/sysinfo';

  execFile
    ( paramsExecutable
    , []
    , function (exitStatus, stdout, stderr) {
        if (exitStatus)
          return callback(new Error(stderr), exitStatus, stdout, stderr);
       
        callback
          ( undefined
          , exitStatus
          , stdout.toString().trim()
          , stderr.toString().trim()
          );
        return;
      }
    );
} 

// Generate a hex representation of a random four byte string.
function genId() {
  return Math.floor(Math.random() * 0xffffffff).toString(16);
};

// vim:ft=javascript
